export const NOTIFICATION_TYPE = {
  INFO: 0,
  WARN: 1,
  ERROR: 2,
};

export const SAVE_MODAL_MODE = {
  SAVE: 1,
  LOAD: 2,
};

export const HELP_PAGE_MODE = {
  CONTROL: 1,
  GAME_SYSTEM: 2,
  STATISTICS: 3,
};

export const REPORT_SUBJECT = {
  // overview
  TOTAL_RATE: 101,
  AVERAGE_RATE: 102,
  CHUNKS_BUFFED: 103,
  TRIPLE_BUFFED: 104,
  DOUBLE_BUFFED: 105,
  UNBUFFED_ACTIVE_CHUNK: 106,
  AVERAGE_MOVE_DURATION: 107,
  AVERAGE_MOVE_RATIO: 108,

  // farm
  ACTIVE_CHUNKS: 201,
  GATHER_RATE: 202,
  PERIOD: 203,
  TOP_STACKS: 204,
  TOTAL_MOVE_DISTANCE: 205,
  MOVE_DURATION: 206,
  MOVE_RATIO: 207,

  // granary
  BUFFED_FARM_COUNT: 301,
  BUFFED_CHUNK_COUNT: 302,
  BUFFED_ACTIVE_CHUNK: 303,

  // drop off buildings
  FARM_DROP_COUNT: 401,
  AVERAGE_DROPOFF_DISTANCE: 402,
};

export const DATA_UNIT = {
  NONE: 0,
  SECOND: 100,
  PER_SECOND: 201,
  PER_MINUTE: 202,
  PERCENTAGE: 300,
  CHUNK: 401,
  TILE: 402,
  FARM: 500,
  TILE_PER_SECOND: 60201,
};
