export const GROUP_MODE = {
  APP_TYPE: 1,
  GENRE: 2,
  CATEGORY: 3,
  FREE_GAME: 4,
  NEVER_PLAYED: 5,
  MY_RECOMMENDATION: 6,
  MY_ACHIEVEMENT: 7,
};
export const SORT_MODE = {
  RELEASE_DATE: 1,
  PRICE: 2,
  MY_RATING: 3,
  MY_GAME_TIME: 4,
  MY_LAST_TIME: 5,
  MY_ACHIEVEMENT: 6,
};
